-- Add detailed profile fields to category tables
ALTER TABLE "Doctor"
  ADD COLUMN IF NOT EXISTS "currentDesignation" TEXT,
  ADD COLUMN IF NOT EXISTS "postAppliedFor" TEXT,
  ADD COLUMN IF NOT EXISTS "submittedOn" TEXT,
  ADD COLUMN IF NOT EXISTS "objections" TEXT,
  ADD COLUMN IF NOT EXISTS "education" JSONB,
  ADD COLUMN IF NOT EXISTS "serviceInformation" JSONB,
  ADD COLUMN IF NOT EXISTS "appointmentDetails" JSONB,
  ADD COLUMN IF NOT EXISTS "probationDetails" TEXT,
  ADD COLUMN IF NOT EXISTS "timeboundPromotions" JSONB,
  ADD COLUMN IF NOT EXISTS "postgraduateQualifications" JSONB,
  ADD COLUMN IF NOT EXISTS "administrativeRoles" JSONB,
  ADD COLUMN IF NOT EXISTS "additionalCharges" JSONB,
  ADD COLUMN IF NOT EXISTS "achievements" JSONB,
  ADD COLUMN IF NOT EXISTS "disciplinaryRecord" JSONB,
  ADD COLUMN IF NOT EXISTS "declaration" JSONB,
  ADD COLUMN IF NOT EXISTS "documents" JSONB;

ALTER TABLE "Nurse"
  ADD COLUMN IF NOT EXISTS "currentDesignation" TEXT,
  ADD COLUMN IF NOT EXISTS "postAppliedFor" TEXT,
  ADD COLUMN IF NOT EXISTS "submittedOn" TEXT,
  ADD COLUMN IF NOT EXISTS "objections" TEXT,
  ADD COLUMN IF NOT EXISTS "education" JSONB,
  ADD COLUMN IF NOT EXISTS "serviceInformation" JSONB,
  ADD COLUMN IF NOT EXISTS "appointmentDetails" JSONB,
  ADD COLUMN IF NOT EXISTS "probationDetails" TEXT,
  ADD COLUMN IF NOT EXISTS "timeboundPromotions" JSONB,
  ADD COLUMN IF NOT EXISTS "postgraduateQualifications" JSONB,
  ADD COLUMN IF NOT EXISTS "administrativeRoles" JSONB,
  ADD COLUMN IF NOT EXISTS "additionalCharges" JSONB,
  ADD COLUMN IF NOT EXISTS "achievements" JSONB,
  ADD COLUMN IF NOT EXISTS "disciplinaryRecord" JSONB,
  ADD COLUMN IF NOT EXISTS "declaration" JSONB,
  ADD COLUMN IF NOT EXISTS "documents" JSONB;

ALTER TABLE "Pharmacist"
  ADD COLUMN IF NOT EXISTS "currentDesignation" TEXT,
  ADD COLUMN IF NOT EXISTS "postAppliedFor" TEXT,
  ADD COLUMN IF NOT EXISTS "submittedOn" TEXT,
  ADD COLUMN IF NOT EXISTS "objections" TEXT,
  ADD COLUMN IF NOT EXISTS "education" JSONB,
  ADD COLUMN IF NOT EXISTS "serviceInformation" JSONB,
  ADD COLUMN IF NOT EXISTS "appointmentDetails" JSONB,
  ADD COLUMN IF NOT EXISTS "probationDetails" TEXT,
  ADD COLUMN IF NOT EXISTS "timeboundPromotions" JSONB,
  ADD COLUMN IF NOT EXISTS "postgraduateQualifications" JSONB,
  ADD COLUMN IF NOT EXISTS "administrativeRoles" JSONB,
  ADD COLUMN IF NOT EXISTS "additionalCharges" JSONB,
  ADD COLUMN IF NOT EXISTS "achievements" JSONB,
  ADD COLUMN IF NOT EXISTS "disciplinaryRecord" JSONB,
  ADD COLUMN IF NOT EXISTS "declaration" JSONB,
  ADD COLUMN IF NOT EXISTS "documents" JSONB;

ALTER TABLE "LabTechnician"
  ADD COLUMN IF NOT EXISTS "currentDesignation" TEXT,
  ADD COLUMN IF NOT EXISTS "postAppliedFor" TEXT,
  ADD COLUMN IF NOT EXISTS "submittedOn" TEXT,
  ADD COLUMN IF NOT EXISTS "objections" TEXT,
  ADD COLUMN IF NOT EXISTS "education" JSONB,
  ADD COLUMN IF NOT EXISTS "serviceInformation" JSONB,
  ADD COLUMN IF NOT EXISTS "appointmentDetails" JSONB,
  ADD COLUMN IF NOT EXISTS "probationDetails" TEXT,
  ADD COLUMN IF NOT EXISTS "timeboundPromotions" JSONB,
  ADD COLUMN IF NOT EXISTS "postgraduateQualifications" JSONB,
  ADD COLUMN IF NOT EXISTS "administrativeRoles" JSONB,
  ADD COLUMN IF NOT EXISTS "additionalCharges" JSONB,
  ADD COLUMN IF NOT EXISTS "achievements" JSONB,
  ADD COLUMN IF NOT EXISTS "disciplinaryRecord" JSONB,
  ADD COLUMN IF NOT EXISTS "declaration" JSONB,
  ADD COLUMN IF NOT EXISTS "documents" JSONB;

ALTER TABLE "RadiologyStaff"
  ADD COLUMN IF NOT EXISTS "currentDesignation" TEXT,
  ADD COLUMN IF NOT EXISTS "postAppliedFor" TEXT,
  ADD COLUMN IF NOT EXISTS "submittedOn" TEXT,
  ADD COLUMN IF NOT EXISTS "objections" TEXT,
  ADD COLUMN IF NOT EXISTS "education" JSONB,
  ADD COLUMN IF NOT EXISTS "serviceInformation" JSONB,
  ADD COLUMN IF NOT EXISTS "appointmentDetails" JSONB,
  ADD COLUMN IF NOT EXISTS "probationDetails" TEXT,
  ADD COLUMN IF NOT EXISTS "timeboundPromotions" JSONB,
  ADD COLUMN IF NOT EXISTS "postgraduateQualifications" JSONB,
  ADD COLUMN IF NOT EXISTS "administrativeRoles" JSONB,
  ADD COLUMN IF NOT EXISTS "additionalCharges" JSONB,
  ADD COLUMN IF NOT EXISTS "achievements" JSONB,
  ADD COLUMN IF NOT EXISTS "disciplinaryRecord" JSONB,
  ADD COLUMN IF NOT EXISTS "declaration" JSONB,
  ADD COLUMN IF NOT EXISTS "documents" JSONB;

ALTER TABLE "SupportStaff"
  ADD COLUMN IF NOT EXISTS "currentDesignation" TEXT,
  ADD COLUMN IF NOT EXISTS "postAppliedFor" TEXT,
  ADD COLUMN IF NOT EXISTS "submittedOn" TEXT,
  ADD COLUMN IF NOT EXISTS "objections" TEXT,
  ADD COLUMN IF NOT EXISTS "education" JSONB,
  ADD COLUMN IF NOT EXISTS "serviceInformation" JSONB,
  ADD COLUMN IF NOT EXISTS "appointmentDetails" JSONB,
  ADD COLUMN IF NOT EXISTS "probationDetails" TEXT,
  ADD COLUMN IF NOT EXISTS "timeboundPromotions" JSONB,
  ADD COLUMN IF NOT EXISTS "postgraduateQualifications" JSONB,
  ADD COLUMN IF NOT EXISTS "administrativeRoles" JSONB,
  ADD COLUMN IF NOT EXISTS "additionalCharges" JSONB,
  ADD COLUMN IF NOT EXISTS "achievements" JSONB,
  ADD COLUMN IF NOT EXISTS "disciplinaryRecord" JSONB,
  ADD COLUMN IF NOT EXISTS "declaration" JSONB,
  ADD COLUMN IF NOT EXISTS "documents" JSONB;

ALTER TABLE "ItHelpdeskStaff"
  ADD COLUMN IF NOT EXISTS "currentDesignation" TEXT,
  ADD COLUMN IF NOT EXISTS "postAppliedFor" TEXT,
  ADD COLUMN IF NOT EXISTS "submittedOn" TEXT,
  ADD COLUMN IF NOT EXISTS "objections" TEXT,
  ADD COLUMN IF NOT EXISTS "education" JSONB,
  ADD COLUMN IF NOT EXISTS "serviceInformation" JSONB,
  ADD COLUMN IF NOT EXISTS "appointmentDetails" JSONB,
  ADD COLUMN IF NOT EXISTS "probationDetails" TEXT,
  ADD COLUMN IF NOT EXISTS "timeboundPromotions" JSONB,
  ADD COLUMN IF NOT EXISTS "postgraduateQualifications" JSONB,
  ADD COLUMN IF NOT EXISTS "administrativeRoles" JSONB,
  ADD COLUMN IF NOT EXISTS "additionalCharges" JSONB,
  ADD COLUMN IF NOT EXISTS "achievements" JSONB,
  ADD COLUMN IF NOT EXISTS "disciplinaryRecord" JSONB,
  ADD COLUMN IF NOT EXISTS "declaration" JSONB,
  ADD COLUMN IF NOT EXISTS "documents" JSONB;

ALTER TABLE "EmtStaff"
  ADD COLUMN IF NOT EXISTS "currentDesignation" TEXT,
  ADD COLUMN IF NOT EXISTS "postAppliedFor" TEXT,
  ADD COLUMN IF NOT EXISTS "submittedOn" TEXT,
  ADD COLUMN IF NOT EXISTS "objections" TEXT,
  ADD COLUMN IF NOT EXISTS "education" JSONB,
  ADD COLUMN IF NOT EXISTS "serviceInformation" JSONB,
  ADD COLUMN IF NOT EXISTS "appointmentDetails" JSONB,
  ADD COLUMN IF NOT EXISTS "probationDetails" TEXT,
  ADD COLUMN IF NOT EXISTS "timeboundPromotions" JSONB,
  ADD COLUMN IF NOT EXISTS "postgraduateQualifications" JSONB,
  ADD COLUMN IF NOT EXISTS "administrativeRoles" JSONB,
  ADD COLUMN IF NOT EXISTS "additionalCharges" JSONB,
  ADD COLUMN IF NOT EXISTS "achievements" JSONB,
  ADD COLUMN IF NOT EXISTS "disciplinaryRecord" JSONB,
  ADD COLUMN IF NOT EXISTS "declaration" JSONB,
  ADD COLUMN IF NOT EXISTS "documents" JSONB;

ALTER TABLE "AdministrationStaff"
  ADD COLUMN IF NOT EXISTS "currentDesignation" TEXT,
  ADD COLUMN IF NOT EXISTS "postAppliedFor" TEXT,
  ADD COLUMN IF NOT EXISTS "submittedOn" TEXT,
  ADD COLUMN IF NOT EXISTS "objections" TEXT,
  ADD COLUMN IF NOT EXISTS "education" JSONB,
  ADD COLUMN IF NOT EXISTS "serviceInformation" JSONB,
  ADD COLUMN IF NOT EXISTS "appointmentDetails" JSONB,
  ADD COLUMN IF NOT EXISTS "probationDetails" TEXT,
  ADD COLUMN IF NOT EXISTS "timeboundPromotions" JSONB,
  ADD COLUMN IF NOT EXISTS "postgraduateQualifications" JSONB,
  ADD COLUMN IF NOT EXISTS "administrativeRoles" JSONB,
  ADD COLUMN IF NOT EXISTS "additionalCharges" JSONB,
  ADD COLUMN IF NOT EXISTS "achievements" JSONB,
  ADD COLUMN IF NOT EXISTS "disciplinaryRecord" JSONB,
  ADD COLUMN IF NOT EXISTS "declaration" JSONB,
  ADD COLUMN IF NOT EXISTS "documents" JSONB;
