#!/usr/bin/env bash

set -euo pipefail

BASE_URL="${BASE_URL:-http://localhost:4000}"
TOKEN="${TOKEN:-}"
USERNAME="${USERNAME:-}"
EMAIL="${EMAIL:-}"
PASSWORD="${PASSWORD:-}"
FILE_PATH="${FILE_PATH:-}"
INSECURE="false"

print_usage() {
  cat <<'USAGE'
Usage:
  scripts/smoke-test-upload.sh [options]

Options:
  --base-url <url>        API base URL (default: http://localhost:4000)
  --token <jwt>           Existing JWT token (skips login)
  --username <username>   Username for /auth/login
  --email <email>         Email for /auth/login
  --password <password>   Password for /auth/login
  --file <path>           File path to upload (default: autogenerated temp file)
  --insecure              Use curl -k for self-signed TLS endpoints
  --help                  Show this help

Auth:
  Provide either:
    1) --token
    2) --username/--password or --email/--password

Environment variable equivalents:
  BASE_URL, TOKEN, USERNAME, EMAIL, PASSWORD, FILE_PATH
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --base-url)
      BASE_URL="$2"
      shift 2
      ;;
    --token)
      TOKEN="$2"
      shift 2
      ;;
    --username)
      USERNAME="$2"
      shift 2
      ;;
    --email)
      EMAIL="$2"
      shift 2
      ;;
    --password)
      PASSWORD="$2"
      shift 2
      ;;
    --file)
      FILE_PATH="$2"
      shift 2
      ;;
    --insecure)
      INSECURE="true"
      shift
      ;;
    --help)
      print_usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      print_usage
      exit 1
      ;;
  esac
done

BASE_URL="${BASE_URL%/}"

CURL_FLAGS=()
if [[ "$INSECURE" == "true" ]]; then
  CURL_FLAGS+=("-k")
fi

cleanup_files=()
cleanup() {
  for file in "${cleanup_files[@]}"; do
    [[ -f "$file" ]] && rm -f "$file"
  done
}
trap cleanup EXIT

make_temp_file() {
  local file
  file="$(mktemp)"
  cleanup_files+=("$file")
  echo "$file"
}

fail_with_response() {
  local title="$1"
  local status="$2"
  local body_file="$3"
  echo "❌ ${title} failed (HTTP ${status})" >&2
  if [[ -s "$body_file" ]]; then
    echo "Response body:" >&2
    cat "$body_file" >&2
  fi
  exit 1
}

if [[ -z "$TOKEN" ]]; then
  if [[ -z "$PASSWORD" ]]; then
    echo "Either --token or --password with --username/--email is required." >&2
    exit 1
  fi
  if [[ -n "$USERNAME" && -n "$EMAIL" ]]; then
    echo "Use either --username or --email, not both." >&2
    exit 1
  fi
  if [[ -z "$USERNAME" && -z "$EMAIL" ]]; then
    echo "Provide --username or --email with --password." >&2
    exit 1
  fi

  identifier="$USERNAME"
  is_email="0"
  if [[ -n "$EMAIL" ]]; then
    identifier="$EMAIL"
    is_email="1"
  fi

  login_payload="$(node -e 'const [id, pass, isEmail] = process.argv.slice(1); const body = isEmail === "1" ? { email: id, password: pass } : { username: id, password: pass }; process.stdout.write(JSON.stringify(body));' "$identifier" "$PASSWORD" "$is_email")"
  login_body="$(make_temp_file)"
  login_status="$(
    curl "${CURL_FLAGS[@]}" -sS \
      -o "$login_body" \
      -w "%{http_code}" \
      -X POST "$BASE_URL/auth/login" \
      -H "Content-Type: application/json" \
      -d "$login_payload"
  )"
  if [[ "$login_status" -lt 200 || "$login_status" -ge 300 ]]; then
    fail_with_response "Login" "$login_status" "$login_body"
  fi

  TOKEN="$(node -e 'const fs=require("fs"); const data=JSON.parse(fs.readFileSync(process.argv[1],"utf8")); if(!data.token){process.stderr.write("Missing token in login response\\n"); process.exit(1);} process.stdout.write(data.token);' "$login_body")"
  echo "✅ Login succeeded"
fi

if [[ -z "$FILE_PATH" ]]; then
  FILE_PATH="$(mktemp "/tmp/etms-upload-smoke-XXXXXX.txt")"
  cleanup_files+=("$FILE_PATH")
  printf 'ETMS upload smoke test at %s\n' "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" > "$FILE_PATH"
fi

if [[ ! -f "$FILE_PATH" ]]; then
  echo "File not found: $FILE_PATH" >&2
  exit 1
fi

upload_body="$(make_temp_file)"
upload_status="$(
  curl "${CURL_FLAGS[@]}" -sS \
    -o "$upload_body" \
    -w "%{http_code}" \
    -X POST "$BASE_URL/uploads" \
    -H "Authorization: Bearer $TOKEN" \
    -F "file=@${FILE_PATH}"
)"
if [[ "$upload_status" -lt 200 || "$upload_status" -ge 300 ]]; then
  fail_with_response "Upload" "$upload_status" "$upload_body"
fi

download_url="$(node -e 'const fs=require("fs"); const data=JSON.parse(fs.readFileSync(process.argv[1],"utf8")); const required=["name","sizeKB","uploadedAt","downloadUrl"]; const missing=required.filter((k)=>data[k]===undefined || data[k]===null || data[k]===""); if(missing.length){process.stderr.write(`Missing fields: ${missing.join(", ")}\n`); process.exit(1);} process.stdout.write(String(data.downloadUrl));' "$upload_body")"

if [[ "$download_url" =~ ^https?:// ]]; then
  resolved_url="$download_url"
else
  resolved_url="${BASE_URL}/${download_url#/}"
fi

download_status="$(
  curl "${CURL_FLAGS[@]}" -sS \
    -o /dev/null \
    -w "%{http_code}" \
    -L "$resolved_url"
)"
if [[ "$download_status" -lt 200 || "$download_status" -ge 399 ]]; then
  echo "❌ Uploaded file URL is not reachable (HTTP ${download_status})" >&2
  echo "URL: ${resolved_url}" >&2
  exit 1
fi

echo "✅ Upload smoke test passed"
echo "   Uploaded file: $FILE_PATH"
echo "   Download URL:  $resolved_url"
